export const actionsEnums = {
	MEMBERS_REQUEST: "MEMBERS_REQUEST",
	MEMBERS_REQUEST_COMPLETED: "MEMBERS_REQUEST_COMPLETED",
	USER_REQUEST: "USER_REQUEST",
	USER_REQUEST_COMPLETED: "USER_REQUEST_COMPLETED",
	ERROR_REQUEST: "ERROR_REQUEST",
};

export interface BaseAction {
	type: string;
	payload?;
}
